name             'duplicity_ng'
maintainer       'Chris Aumann'
maintainer_email 'me@chr4.org'
license          'GNU Public License 3.0'
description      'Installs/Configures duplicity_ng'
long_description 'Installs/Configures duplicity_ng'
version          '0.1.0'
